### ISSUE TITLE
Some user interface improvements

### ISSUE THREAD

**Issue by marcoriol** [Learning-Dashboard/LD-Taiga-frontend#1]
- [x] buttons that show the present and historical views should be the other way around: The clock with an arrow should show historical view, whereas the other should show present view.
- [x] In Historical view, the graphs have a legend with a "First dataset" label that is not needed. It can be removed. 
- [x] In Historical view, the name of the Strategic Indicators, quality factors, etc. is their ID (e.g. "backlogmanagement"), but should be it's name (e.g. "Backlog Management") as shown in the present view.
- [x] In the Present view, maybe the numbers could have "%" ? i.e. 7 --> 7%
- [x] Quality factors have filters in the historical view, but not in the present view (it should be added). The filters should be presented by their name (e.g. "Backlog Management") instead of their ID. -
- [x] It seems that the filters in the Quality factors are incomplete
- [x] In the present view, the graphs of project metrics are not always well aligned/centered. Some of them are moved towards the left.
- [x] The name "metrics evaluation" should be changed to "team metrics"

**Comment by MissterP** [comment]
The task related to user Metrics has been moved to a  issue #17 .
